[project]
name = 'amm'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'

[contracts.sip-010-trait-ft-standard]
path = 'contracts/sip-010-trait-ft-standard.clar'
clarity_version = 4
epoch = 'latest'
[contracts.amm]
path = 'contracts/amm.clar'
clarity_version = 4
epoch = 'latest'

[contracts.mock-token]
path = 'contracts/mock-token.clar'
clarity_version = 4
epoch = 'latest'
[repl.analysis]
passes = ['check_checker']

[contracts.mock-token-2]
path = 'contracts/mock-token-2.clar'
clarity_version = 4
epoch = 'latest'

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
